### ISSUE TITLE
NPE for com.appodealx.mraid.MraidInterstitial.setShowingActivity

### ISSUE THREAD

**Issue by ominfowave** [appodeal/appodeal-android-demo#17]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.appodealx.mraid.MraidInterstitial.setShowingActivity(com.appodealx.mraid.MraidActivity)' on a null object reference
       at com.appodealx.mraid.MraidActivity.finishActivity(Unknown Source)
       at com.appodealx.mraid.MraidActivity.onBackPressed(Unknown Source)
       at android.app.Activity.onKeyUp(Activity.java:2483)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2685)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2736)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4135)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4097)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3852)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3828)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3989)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2253)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1874)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1865)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2230)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I am using appodeal version 2.4.2 and there many crash with error log mention above

**Comment by BaxterZA** [comment]
Hi @ominfowave! This issue was fixed in 2.4.3 version, you can find it here https://www.appodeal.com/sdk/android_beta.
Thank you!
