### ISSUE TITLE
StartAppSDK crash

### ISSUE THREAD

**Issue by gvozditskiy** [appodeal/appodeal-android-demo#18]
I periodically receive "NullPointerException Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference" crash reports 

```Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
       at com.startapp.android.publish.ads.a.b.a(StartAppSDK:83)
       at com.startapp.android.publish.adsCommon.activities.OverlayActivity.a(StartAppSDK:70)
       at com.startapp.android.publish.adsCommon.activities.OverlayActivity.onCreate(StartAppSDK:60)
       at android.app.Activity.performCreate(Activity.java:6679)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

**Comment by BaxterZA** [comment]
Hi, @gvozditskiy !
On which version of Appodeal SDK this crash occurs?

**Comment by gvozditskiy** [comment]
@BaxterZA Appodeal Android SDK 2.1.11
Everything is made as described [here](https://www.appodeal.com/sdk/documentation?framework=1&full=1&platform=1)

**Comment by BaxterZA** [comment]
@gvozditskiy You can try out our new beta version https://www.appodeal.com/sdk/android_beta where StartApp SDK was updated.

**Comment by gvozditskiy** [comment]
@BaxterZA is it stable enough to use in production?

**Comment by BaxterZA** [comment]
@gvozditskiy Yes, it was tested by our QA and already used in production by other publishers. And it's the only way to get updated StartApp SDK. Or you can disable StartApp and continue using 2.1.11 version

**Comment by gvozditskiy** [comment]
@BaxterZA ok, thank you
