### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: 

### ISSUE THREAD

**Issue by ominfowave** [appodeal/appodeal-android-demo#3]
Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at com.appodeal.ads.a.onActivityPaused(Unknown Source)
       at android.app.Application.dispatchActivityPaused(Application.java:247)
       at android.app.Activity.onPause(Activity.java:1652)
       at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:442)

there are approx 25 report on fabric

**Comment by scerelli** [comment]
Same here:

```07-03 17:26:16.515 11485 11561 W art     : Throwing OutOfMemoryError "Failed to allocate a 92 byte allocation with 3800 free bytes and 3KB until OOM" (recursive case)
07-03 17:26:16.515 11485 11485 I art     : WaitForGcToComplete blocked for 243.582ms for cause Alloc
07-03 17:26:16.515 11485 11485 I art     : Starting a blocking GC Alloc
07-03 17:26:16.516 11485 11494 I art     : WaitForGcToComplete blocked for 520.957ms for cause Alloc
07-03 17:26:16.516 11485 11494 I art     : Starting a blocking GC Alloc
07-03 17:26:16.516 11485 11494 I art     : Starting a blocking GC Alloc
07-03 17:26:16.518 11485 11485 I art     : Waiting for a blocking GC Alloc
07-03 17:26:16.539 11485 11561 W art     : "OkHttp http://download.blender.org/..." prio=5 tid=35 Runnable
07-03 17:26:16.539 11485 11561 W art     :   | group="main" sCount=0 dsCount=0 obj=0x32c14430 self=0xd85f8000
07-03 17:26:16.539 11485 11561 W art     :   | sysTid=11561 nice=0 cgrp=default sched=0/0 handle=0xcff84920
07-03 17:26:16.539 11485 11561 W art     :   | state=R schedstat=( 0 0 0 ) utm=275 stm=282 core=3 HZ=100
07-03 17:26:16.539 11485 11561 W art     :   | stack=0xcfe82000-0xcfe84000 stackSize=1038KB
07-03 17:26:16.539 11485 11561 W art     :   | held mutexes= "mutator lock"(shared held)
```

**Comment by BaxterZA** [comment]
Hi ominfowave! We'll remove unnecessary thread creation in the next version of our SDK.
Thanks!
