### ISSUE TITLE
onNativeClicked crash on release mode

### ISSUE THREAD

**Issue by DennisMostajo** [appodeal/appodeal-android-demo#5]
Hi guys

I have an issue, I added appodeal 2.0.2 according to the apodeal-android-demo to my project and everything is working correctly when doing test, in my project I'm using only native ads,the only problem I have is that when I generated the release signed apk, when I click on an ad, the application Does crash and shows me these logs, any help that can be?, Thanks!

`08-24 16:31:36.856 23468-23468/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.DennisTest.app, PID: 23468
                                                   android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
                                                       at android.view.ViewRootImpl.setView(ViewRootImpl.java:680)
                                                       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:288)
                                                       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                       at android.app.Dialog.show(Dialog.java:312)
                                                       at android.app.ProgressDialog.show(ProgressDialog.java:116)
                                                       at android.app.ProgressDialog.show(ProgressDialog.java:99)
                                                       at android.app.ProgressDialog.show(ProgressDialog.java:94)
                                                       at com.appodeal.ads.native_ad.d$a.a(Unknown Source)
                                                       at com.appodeal.ads.ah.onClick(Unknown Source)
                                                       at android.view.View.performClick(View.java:5156)
                                                       at android.view.View$PerformClick.run(View.java:20755)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:145)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5835)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
08-24 16:31:37.216 955-24913/? E/android.os.Debug: !@Dumpstate > sdumpstate -k -t -z -d -o /data/log/dumpstate_app_error`

**Comment by BaxterZA** [comment]
Hi, DennisMostajo!
You need to create view with Activity context instead of Application, which you pass to registerViewForInteraction method.
Thanks!

**Comment by DennisMostajo** [comment]
Thanks for the reply BaxterZA, I have implemented this class which I use according to the demo example: 

` @EViewGroup(R.layout.a_postlist_ad_container) // linear layout
public class AdItemView extends BaseItemView<NativeAd> {
    @ViewById(R.id.a_postlist_ad_container)
    public LinearLayout container;

    @ViewById(R.id.post_tv_time)
    TextView tvTime;

    @ViewById(R.id.post_tv_user_name)
    TextView tvTitle;

    @ViewById(R.id.post_tv_summary)
    TextView tvDescription;

    @ViewById(R.id.post_iv_user_picture)
    ImageView ivIcon;

    @ViewById(R.id.tv_call_action)
    TextView tvCallAction;

    @ViewById(R.id.cv_native_ad_view) // android.support.v7.widget.CardView
    CardView cardView;

    public AdItemView(Context context) {
        super(context);
        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(
                LayoutParams.MATCH_PARENT,
                LayoutParams.WRAP_CONTENT);
        setLayoutParams(params);
    }

    @Override
    public void bind(NativeAd nativeAd) {
        tvTime.setText(Bebler.context.getString(R.string.native_ad_advert_text));
        tvTitle.setText(nativeAd.getTitle());
        Log.e("AdItemView:", "tvTitle " + nativeAd.getTitle());
        tvDescription.setText(nativeAd.getDescription());
        ImageLoader.getInstance().displayImage(nativeAd.getIconUrl(), ivIcon);
        tvCallAction.setText(nativeAd.getCallToAction());
        View providerView = nativeAd.getProviderView(DennisTest.context);
        if (providerView != null) {
            container.addView(providerView);
        }
        nativeAd.registerViewForInteraction(cardView);
        Log.e("AdItemView:", "registerViewForInteraction");
    }
}`

when I run the application in debug, it works perfectly recognizes the click on the ad, but when I run with a release signed apk, crashes when I click on the ad, I don't know what could be

**Comment by BaxterZA** [comment]
Hi, DennisMostajo!
Can you send release signed apk to email az@appodeal.com? I'll check it.
Thanks!

**Comment by DennisMostajo** [comment]
Hi, Baxter, I sent you the release signed apk to your mail, I will be attentive to your response many thanks!

**Comment by DennisMostajo** [comment]
Hi Alexandr:

You were right! , the _cardview.getContext ()_ was returned null, and I replaced it by the container, other than that in my adapter also used the context of the application and I changed it for the activity as you suggested:
 ```
View providerView = nativeAd.getProviderView(container.context); //---- linear layout parent container from cardView
    if (providerView != null) {
        container.addView(providerView);
    }
    nativeAd.registerViewForInteraction(cardView);
 @Override
    protected BaseItemView onCreateItemView(ViewGroup parent, int viewType) {
        ListAdaptersViewTypes type = ListAdaptersViewTypes.values()[viewType];
        switch (type) {
            case AD:
//                return AdItemView_.build(App.context);  // before Aplication context
                return AdItemView_.build(parent.getContext()); // now Activity context
            default:
                return ItemView_.build(App.context, new CustomPostItemViewListener());
        }
    }
```
thanks a lot!, it was omitted on debug way but not in release way, with this the problem was solved, your kung fu is the best!


Best Regards!
