### ISSUE TITLE
Appodeal INTERSTITIAL Not loading Android

### ISSUE THREAD

**Issue by usestrike** [appodeal/appodeal-android-demo#7]
I am calling : Appodeal.show(Appodeal.INTERSTITIAL);

I am getting this error : 

W/Ads: Invoke Firebase method getInstance error.
                                                                           java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurement" on path: DexPathList[[dex file "/data/user/0/package.name/app_working/yandex.dex", dex file "/data/user/0/package.name/app_working/startapp.dex", dex file "/data/user/0/package.name/app_working/revmob.dex", dex file "/data/user/0/package.name/app_working/flurry.dex", dex file "/data/user/0/package.name/app_working/facebook.dex", zip file "/data/app/package.name/base.apk"],nativeLibraryDirectories=[/data/app/package.name/lib/arm, /vendor/lib, /system/lib]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                               at com.google.android.gms.ads.internal.scionintegration.b.a(:com.google.android.gms.DynamiteModulesA@11509438:167)
                                                                               at com.google.android.gms.ads.internal.scionintegration.b.a(:com.google.android.gms.DynamiteModulesA@11509438:152)
                                                                               at com.google.android.gms.ads.internal.scionintegration.b.g(:com.google.android.gms.DynamiteModulesA@11509438:43)
                                                                               at com.google.android.gms.ads.internal.request.c.a(:com.google.android.gms.DynamiteModulesA@11509438:47)
                                                                               at com.google.android.gms.ads.internal.util.b.run(:com.google.android.gms.DynamiteModulesA@11509438:4)
                                                                               at com.google.android.gms.ads.internal.util.af.call(:com.google.android.gms.DynamiteModulesA@11509438:3)
                                                                               at com.google.android.gms.ads.internal.util.ag.run(:com.google.android.gms.DynamiteModulesA@11509438:3)
                                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                           	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.measurement.AppMeasurement
                                                                               at java.lang.Class.classForName(Native Method)
                                                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                               		... 13 more
                                                                            Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
W/Ads: The Google Mobile Ads SDK will not integrate with Firebase. Admob/Firbase integration requires the latest Firebase SDK jar, but Firebase SDK is either missing or out of date

**Comment by NikitaCherep** [comment]
You use this project without modification?

**Comment by usestrike** [comment]
No i just follow this instructions : https://www.appodeal.com/sdk/documentation?framework=1&full=1

issue is related Firebase. But in my project i haven't included firebase.

**Comment by NikitaCherep** [comment]
Does this error crash the application?

**Comment by usestrike** [comment]
NO, its working fine. 

But It is not showing any ads.

**Comment by NikitaCherep** [comment]
You use your "app_key" and "bundle" or from test app?

**Comment by usestrike** [comment]
yes mine

**Comment by NikitaCherep** [comment]
You see test ads?

**Comment by usestrike** [comment]
yes, i can see ads from admob. But not any other ads platfrom.

**Comment by NikitaCherep** [comment]
Write support from site

**Comment by usestrike** [comment]
Ok
