### ISSUE TITLE
Classes not found after proguard added

### ISSUE THREAD

**Issue by ArunPandiyan** [appodeal/appodeal-android-demo#8]
These are errors showing after initialization.

` D/Appodeal: SDK v2.1.4 initialized, appKey: sdfsdfsexxxxxxx0236252941c0e7d6e0a9dcc6bb1d44971, package name: bitsie.playmee.musicplayer.free
10-24 22:44:24.009 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.b.a.a(android.app.Activity) (AppodealController.java:92)
10-24 22:44:24.009 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.FragmentsHostActivity.onCreate(android.os.Bundle) (FragmentsHostActivity.java:112)
10-24 22:44:24.010 16322-16322/? I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.appnext.appnextsdk.API.AppnextAPI$AppnextAdListener" on path: DexPathList[[zip file "/data/app/bitsie.playmee.musicplayer.free-1/base.apk"],nativeLibraryDirectories=[/data/app/bitsie.playmee.musicplayer.free-1/lib/arm, /data/app/bitsie.playmee.musicplayer.free-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
10-24 22:44:24.010 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.b.a.a(android.app.Activity) (AppodealController.java:92)
10-24 22:44:24.010 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.FragmentsHostActivity.onCreate(android.os.Bundle) (FragmentsHostActivity.java:112)
10-24 22:44:24.013 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.b.a.a(android.app.Activity) (AppodealController.java:92)
10-24 22:44:24.013 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.FragmentsHostActivity.onCreate(android.os.Bundle) (FragmentsHostActivity.java:112)
10-24 22:44:24.013 16322-16322/? I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.appnext.appnextsdk.API.Native" on path: DexPathList[[zip file "/data/app/bitsie.playmee.musicplayer.free-1/base.apk"],nativeLibraryDirectories=[/data/app/bitsie.playmee.musicplayer.free-1/lib/arm, /data/app/bitsie.playmee.musicplayer.free-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
10-24 22:44:24.013 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.b.a.a(android.app.Activity) (AppodealController.java:92)
10-24 22:44:24.013 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.FragmentsHostActivity.onCreate(android.os.Bundle) (FragmentsHostActivity.java:112)
10-24 22:44:24.017 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.b.a.a(android.app.Activity) (AppodealController.java:92)
10-24 22:44:24.017 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.FragmentsHostActivity.onCreate(android.os.Bundle) (FragmentsHostActivity.java:112)
10-24 22:44:24.017 16322-16322/? I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.avocarrot.androidsdk.AvocarrotCustomListener" on path: DexPathList[[zip file "/data/app/bitsie.playmee.musicplayer.free-1/base.apk"],nativeLibraryDirectories=[/data/app/bitsie.playmee.musicplayer.free-1/lib/arm, /data/app/bitsie.playmee.musicplayer.free-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
10-24 22:44:24.017 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.b.a.a(android.app.Activity) (AppodealController.java:92)
10-24 22:44:24.017 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.FragmentsHostActivity.onCreate(android.os.Bundle) (FragmentsHostActivity.java:112)
10-24 22:44:24.024 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.b.a.a(android.app.Activity) (AppodealController.java:92)
10-24 22:44:24.024 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.FragmentsHostActivity.onCreate(android.os.Bundle) (FragmentsHostActivity.java:112)
10-24 22:44:24.024 16322-16322/? I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.inmobi.ads.InMobiNative$NativeAdListener" on path: DexPathList[[zip file "/data/app/bitsie.playmee.musicplayer.free-1/base.apk"],nativeLibraryDirectories=[/data/app/bitsie.playmee.musicplayer.free-1/lib/arm, /data/app/bitsie.playmee.musicplayer.free-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
10-24 22:44:24.024 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.b.a.a(android.app.Activity) (AppodealController.java:92)
10-24 22:44:24.024 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.FragmentsHostActivity.onCreate(android.os.Bundle) (FragmentsHostActivity.java:112)
10-24 22:44:24.028 16322-16322/? D/Appodeal: Exception
                                             java.lang.reflect.InvocationTargetException
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at com.appodeal.ads.Native.a(Unknown Source)
                                                 at com.appodeal.ads.Native.b(Unknown Source)
                                                 at com.appodeal.ads.Native.a(Unknown Source)
                                                 at com.appodeal.ads.Native.a(Unknown Source)
                                                 at com.appodeal.ads.Native.a(Unknown Source)
                                                 at com.appodeal.ads.Native.a(Unknown Source)
                                                 at com.appodeal.ads.Appodeal.initialize(Unknown Source)
                                                 at bitsie.playmee.musicplayer.free.b.a.a(AppodealController.java:92)
                                                 at bitsie.playmee.musicplayer.free.FragmentsHostActivity.onCreate(FragmentsHostActivity.java:112)
                                                 at android.app.Activity.performCreate(Activity.java:6760)
                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2686)
                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819)
                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                 at android.os.Looper.loop(Looper.java:154)
                                                 at android.app.ActivityThread.main(ActivityThread.java:6321)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                              Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/inmobi/sdk/InMobiSdk;
                                                 at com.appodeal.ads.networks.l.a(Unknown Source)
                                                 at com.appodeal.ads.native_ad.i.c(Unknown Source)
                                                 at com.appodeal.ads.d.b(Unknown Source)
                                                 at com.appodeal.ads.native_ad.i.getInstance(Unknown Source)
                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                 at com.appodeal.ads.Native.a(Unknown Source) 
                                                 at com.appodeal.ads.Native.b(Unknown Source) 
                                                 at com.appodeal.ads.Native.a(Unknown Source) 
                                                 at com.appodeal.ads.Native.a(Unknown Source) 
                                                 at com.appodeal.ads.Native.a(Unknown Source) 
                                                 at com.appodeal.ads.Native.a(Unknown Source) 
                                                 at com.appodeal.ads.Appodeal.initialize(Unknown Source) 
                                                 at bitsie.playmee.musicplayer.free.b.a.a(AppodealController.java:92) 
                                                 at bitsie.playmee.musicplayer.free.FragmentsHostActivity.onCreate(FragmentsHostActivity.java:112) 
                                                 at android.app.Activity.performCreate(Activity.java:6760) 
                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134) 
                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2686) 
                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819) 
                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 
                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                 at android.os.Looper.loop(Looper.java:154) 
                                                 at android.app.ActivityThread.main(ActivityThread.java:6321) 
                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "com.inmobi.sdk.InMobiSdk" on path: DexPathList[[zip file "/data/app/bitsie.playmee.musicplayer.free-1/base.apk"],nativeLibraryDirectories=[/data/app/bitsie.playmee.musicplayer.free-1/lib/arm, /data/app/bitsie.playmee.musicplayer.free-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                 at com.appodeal.ads.networks.l.a(Unknown Source) 
                                                 at com.appodeal.ads.native_ad.i.c(Unknown Source) 
                                                 at com.appodeal.ads.d.b(Unknown Source) 
                                                 at com.appodeal.ads.native_ad.i.getInstance(Unknown Source) 
                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                 at com.appodeal.ads.Native.a(Unknown Source) 
                                                 at com.appodeal.ads.Native.b(Unknown Source) 
                                                 at com.appodeal.ads.Native.a(Unknown Source) 
                                                 at com.appodeal.ads.Native.a(Unknown Source) 
                                                 at com.appodeal.ads.Native.a(Unknown Source) 
                                                 at com.appodeal.ads.Native.a(Unknown Source) 
                                                 at com.appodeal.ads.Appodeal.initialize(Unknown Source) 
                                                 at bitsie.playmee.musicplayer.free.b.a.a(AppodealController.java:92) 
                                                 at bitsie.playmee.musicplayer.free.FragmentsHostActivity.onCreate(FragmentsHostActivity.java:112) 
                                                 at android.app.Activity.performCreate(Activity.java:6760) 
                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134) 
                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2686) 
                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819) 
                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 
                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                 at android.os.Looper.loop(Looper.java:154) 
                                                 at android.app.ActivityThread.main(ActivityThread.java:6321) 
                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
10-24 22:44:24.029 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.b.a.a(android.app.Activity) (AppodealController.java:92)
10-24 22:44:24.029 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.FragmentsHostActivity.onCreate(android.os.Bundle) (FragmentsHostActivity.java:112)
10-24 22:44:24.029 16322-16322/? I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.millennialmedia.NativeAd$NativeListener" on path: DexPathList[[zip file "/data/app/bitsie.playmee.musicplayer.free-1/base.apk"],nativeLibraryDirectories=[/data/app/bitsie.playmee.musicplayer.free-1/lib/arm, /data/app/bitsie.playmee.musicplayer.free-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
10-24 22:44:24.030 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.b.a.a(android.app.Activity) (AppodealController.java:92)
10-24 22:44:24.030 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.FragmentsHostActivity.onCreate(android.os.Bundle) (FragmentsHostActivity.java:112)
10-24 22:44:24.036 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.b.a.a(android.app.Activity) (AppodealController.java:92)
10-24 22:44:24.036 16322-16322/? I/art:     at void bitsie.playmee.musicplayer.free.FragmentsHostActivity.onCreate(android.os.Bundle) (FragmentsHostActivity.java:112)
10-24 22:44:24.036 16322-16322/? I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.startapp.android.publish.adsCommon.adListeners.AdEventListener" on path: DexPathList[[zip file "/data/app/bitsie.playmee.musicplayer.free-1/base.apk"],nativeLibraryDirectories=[/data/app/bitsie.playmee.musicplayer.free-1/lib/arm, /data/app/bitsie.playmee.musicplayer.free-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]`

and my proguard is this

`# Appodeal
-keep class com.appodeal.** { *; }
-keep class org.nexage.** { *; }
-keepattributes EnclosingMethod, InnerClasses, Signature, JavascriptInterface

# Amazon
-keep class com.amazon.** { *; }
-dontwarn com.amazon.**

# Mopub
-keep public class com.mopub.**
-keepclassmembers class com.mopub.** { public *; }
-dontwarn com.mopub.**
-keep class * extends com.mopub.mobileads.CustomEventBanner {}
-keepclassmembers class com.mopub.mobileads.CustomEventBannerAdapter {!private !public !protected *;}
-keep class * extends com.mopub.mobileads.CustomEventInterstitial {}
-keep class * extends com.mopub.nativeads.CustomEventNative {}
-keep class * extends com.mopub.mobileads.CustomEventRewardedVideo {}
-dontwarn com.mopub.volley.toolbox.**
-keepclassmembers class ** { @com.mopub.common.util.ReflectionTarget *; }

# Applovin
-keep class com.applovin.** { *; }
-dontwarn com.applovin.**

# Facebook
-keep class com.facebook.ads.** { *; }
-keeppackagenames com.facebook.*
-dontwarn com.facebook.ads.**

# Chartboost
-keep class com.chartboost.** { *; }
-dontwarn com.chartboost.**

# Unity Ads
-keepattributes SourceFile,LineNumberTable
-keep class com.unity3d.** { *; }
-dontwarn com.unity3d.**

# Yandex
-keep class com.yandex.metrica.** { *; }
-dontwarn com.yandex.metrica.**
-keep class com.yandex.mobile.ads.** { *; }
-dontwarn com.yandex.mobile.ads.**
-keepattributes *Annotation*

# StartApp
-keep class com.startapp.** { *;}
-dontwarn com.startapp.**
-keepattributes Exceptions, InnerClasses, Signature, Deprecated, SourceFile, LineNumberTable, *Annotation*, EnclosingMethod

# Flurry
-keep class com.flurry.** { *; }
-dontwarn com.flurry.**
-keepattributes *Annotation*,EnclosingMethod,Signature
-keepclasseswithmembers class * {
  public <init>(android.content.Context, android.util.AttributeSet, int);
}

# Avocarrot
-keep class com.avocarrot.** { *; }
-keepclassmembers class com.avocarrot.** { *; }
-dontwarn com.avocarrot.**
-keep public class * extends android.view.View {
  public <init>(android.content.Context);
  public <init>(android.content.Context, android.util.AttributeSet);
  public <init>(android.content.Context, android.util.AttributeSet, int);
  public void set*(...);
}

# Adcolony
-keep class com.jirbo.adcolony.** { *;}
-keep class com.adcolony.** { *;}
-keep class com.immersion.** { *;}
-dontnote com.immersion.**
-dontwarn android.webkit.**
-dontwarn com.jirbo.adcolony.**
-dontwarn com.adcolony.**

# Vungle
-keepattributes *Annotation*, Signature
-keep class com.vungle.** { *;}
-dontwarn com.vungle.**
-keep class com.moat.analytics.mobile.vng.** { *;}
-keep class dagger.**
-keep class de.greenrobot.event.**
-keep class javax.inject.**
-keep class rx.**

# MyTarget
-keep class com.my.target.** { *; }
-dontwarn com.my.target.**

# Admob
-keep class com.google.android.gms.ads.** { *; }

# Tapjoy
-keep class com.tapjoy.** { *; }
-dontwarn com.tapjoy.**

# IronSource
-keepclassmembers class com.ironsource.sdk.controller.IronSourceWebView$JSInterface { public *; }
-keepclassmembers class * implements android.os.Parcelable { public static final android.os.Parcelable$Creator *; }
-keep class com.ironsource.** { *; }
-dontwarn com.ironsource.**

# AdColonyV3
-keepclassmembers class * { @android.webkit.JavascriptInterface <methods>; }
-keep class com.adcolony.** { *; }
-dontwarn com.adcolony.**
-dontwarn android.app.Activity

#Appnext
-keep class com.appnext.** { *; }
-dontwarn com.appnext.**

# Inmobi
-keep class com.inmobi.** { *; }
-dontwarn com.inmobi.**
-dontwarn com.squareup.picasso.**
-keep class com.squareup.picasso.** {*;}
-dontwarn com.squareup.picasso.**
-dontwarn com.squareup.okhttp.**
-keep class com.moat.** {*;}
-dontwarn com.moat.**

# MMdeia
-keepclassmembers class com.millennialmedia** {public *;}
-keep class com.millennialmedia**
-dontwarn com.millennialmedia.**

# Ogury
-dontwarn io.presage.**
-dontnote io.presage.**
-dontwarn shared_presage.**
-dontwarn org.codehaus.**
-keepattributes Signature
-keep class shared_presage.** { *; }
-keep class io.presage.** { *; }
-keepclassmembers class io.presage.** { *; }
-keepattributes *Annotation*
-keepattributes JavascriptInterface
-keepclassmembers class * {
  @android.webkit.JavascriptInterface <methods>;
}
-dontnote okhttp3.**
-dontnote okio.**
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.ParametersAreNonnullByDefault

-dontnote sun.misc.Unsafe
-dontnote android.net.http.*

-dontnote org.apache.commons.codec.**
-dontnote org.apache.http.**

-dontwarn org.apache.commons.collections.BeanMap
-dontwarn java.beans.**
-dontnote com.google.gson.**
-keepclassmembers class * implements java.io.Serializable {
  static final long serialVersionUID;
  private static final java.io.ObjectStreamField[] serialPersistentFields;
  private void writeObject(java.io.ObjectOutputStream);
  private void readObject(java.io.ObjectInputStream);
  java.lang.Object writeReplace();
  java.lang.Object readResolve();
}

# Google
-keep class com.google.android.gms.common.GooglePlayServicesUtil {*;}
-keep class com.google.android.gms.ads.identifier.** { *; }
-dontwarn com.google.android.gms.**

# Legacy
-keep class org.apache.http.** { *; }
-dontwarn org.apache.http.**
-dontwarn android.net.http.**

# Google Play Services library
-keep class * extends java.util.ListResourceBundle {
  protected Object[][] getContents();
}
-keep public class com.google.android.gms.common.internal.safeparcel.SafeParcelable {
  public static final *** NULL;
}
-keepnames class * implements android.os.Parcelable
-keepclassmembers class * implements android.os.Parcelable {
  public static final *** CREATOR;
}
-keep @interface android.support.annotation.Keep
-keep @android.support.annotation.Keep class *
-keepclasseswithmembers class * {
  @android.support.annotation.Keep <fields>;
}
-keepclasseswithmembers class * {
  @android.support.annotation.Keep <methods>;
}
-keep @interface com.google.android.gms.common.annotation.KeepName
-keepnames @com.google.android.gms.common.annotation.KeepName class *
-keepclassmembernames class * {
  @com.google.android.gms.common.annotation.KeepName *;
}
-keep @interface com.google.android.gms.common.util.DynamiteApi
-keep public @com.google.android.gms.common.util.DynamiteApi class * {
  public <fields>;
  public <methods>;
}
-keep class com.google.android.gms.common.GooglePlayServicesNotAvailableException {*;}
-keep class com.google.android.gms.common.GooglePlayServicesRepairableException {*;}

# Google Play Services library 9.0.0 only
-dontwarn android.security.NetworkSecurityPolicy
-keep public @com.google.android.gms.common.util.DynamiteApi class * { *; }

# support-v4
-keep class android.support.v4.app.Fragment { *; }
-keep class android.support.v4.app.FragmentActivity { *; }
-keep class android.support.v4.app.FragmentManager { *; }
-keep class android.support.v4.app.FragmentTransaction { *; }
-keep class android.support.v4.content.ContextCompat { *; }
-keep class android.support.v4.content.LocalBroadcastManager { *; }
-keep class android.support.v4.util.LruCache { *; }
-keep class android.support.v4.view.PagerAdapter { *; }
-keep class android.support.v4.view.ViewPager { *; }
-keep class android.support.v4.content.ContextCompat { *; }

# support-v7-recyclerview
-keep class android.support.v7.widget.RecyclerView { *; }
-keep class android.support.v7.widget.LinearLayoutManager { *; }
-keep class android.support.v4.** { *; }
-keep interface android.support.v4.app.** { *; }
-keep class android.support.v7.app.** { *; }
-keep interface android.support.v7.app.** { *; }
-keep class com.bumptech.glide.integration.volley.VolleyGlideModule
-keep public class * implements com.bumptech.glide.module.GlideModule

-dontwarn org.apache.commons.**
-dontwarn org.apache.regexp.**
-dontwarn com.tapjoy.internal.**
-dontwarn org.apache.commons.**
-dontwarn com.calldorado.android.**
-keep class com.pollfish.** { *; }
-keep class com.tapjoy.** { *; }
-keepattributes JavascriptInterface
-keepattributes EnclosingMethod
-keepattributes *Annotation*
-keep class * extends java.util.ListResourceBundle {
protected Object[][] getContents();
}
-keep public class com.google.android.gms.common.internal.safeparcel.SafeParcelable {
public static final *** NULL;
}

-keep class pe.appa.stats.** { *; }
-keep interface pe.appa.stats.** { *; }
-keep public enum pe.appa.stats.AppApeStats$** {
**[] $VALUES;
public *;
}
-keep public class * extends android.content.pm.** { *; }
-keep public class * implements android.content.pm.** { *; }
-assumenosideeffects class android.util.Log {
public static *** d(...);
public static *** v(...);
public static *** i(...);
public static *** w(...);
public static *** e(...);
}
 -ignorewarnings
-keepnames @com.google.android.gms.common.annotation.KeepName class *
-keepclassmembernames class * {
@com.google.android.gms.common.annotation.KeepName *;
}
-keepnames class * implements android.os.Parcelable {
public static final ** CREATOR;
}
-keep class com.google.android.gms.ads.identifier.** { *; }
-dontwarn com.tapjoy.internal.**
-keep class com.facebook.ads.** { *; }
-keep class org.apache.http.** { *; }
-dontwarn org.apache.http.**
-keepattributes Signature
-keep class com.facebook.android.*
-keep class android.webkit.WebViewClient
-keep class * extends android.webkit.WebViewClient
-keepclassmembers class * extends android.webkit.WebViewClient {
    <methods>;
}
-dontwarn net.adxmi.android.**
-keep class net.adxmi.android.** {
    *;
}
`
it is copied from the website only. No modification. how to clear this one?

**Comment by NikitaCherep** [comment]
Hello, @ArunPandiyan. May you send test apk?
